
networks:
  frontend:
    ipam:
      config:
        - subnet: 172.20.0.0/24
services:
  server:
    build:
      context: .
      dockerfile:  ./server/Dockerfile
    restart: always
    networks:
      frontend:
        ipv4_address: 172.20.0.100
    environment:
      - IP=172.20.0.100
  client:
    build:
      context: .
      dockerfile:  ./client/Dockerfile
    restart: always
    links:
      - server
    networks:
      frontend:
    deploy:
      mode: replicated
      replicas: 3
